server:
  port: 8088

regexp:
  phone: "^\\+?([1-9]{2})?[\\s]?[(]?[\\d]+[\\s)]?[\\s-_]?([\\d]{3})?[\\s-_]?([\\d]{2})?[\\s-_]?([\\d]{2})?\\b"
  email: "^\\b[a-zA-Z][a-zA-Z-0-9]*?@[a-z]+?\\Q.\\E[a-z]+\\b"
  price: "\\b(\\D|([\\w]{3}\\s))?[1-9]+?(([,.\\s]?([\\d]+))+)?(\\s[\\w]{3})?\\b"